FROM node:18.9.0 as builder
WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --silent

COPY . .

RUN yarn build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]