version: "3.9"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.test
        container_name: client-dev
        image: client-dev-image
        volumes:
            - /app/node_modules
            - ./client:/app
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.test
        container_name: server-dev
        image: server-dev-image
        volumes:
            - /app/node_modules
            - ./server:/app