version: "3.9"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        container_name: client-dev
        image: client-dev-image
        env_file: .env.dev
        environment: 
            - CHOKIDAR_USEPOLLING=true
        restart: always
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - 3000:3000
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        container_name: server-dev
        image: server-dev-image
        env_file: 
            - .env.dev
        restart: always
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 8080:8080