FROM node:18-alpine as builder

RUN mkdir -p /app
WORKDIR /app

ENV NODE_ENV=production

RUN npm i -g @nestjs/cli --silent
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake

COPY ./package.json ./
COPY ./yarn.lock ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./
EXPOSE $SERVER_PORT
CMD ["node", "dist/main"]