FROM node:18-alpine
RUN mkdir -p /app
WORKDIR /app

ENV NODE_ENV=test

RUN npm i -g @nestjs/cli --silent
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

CMD ["yarn", "test"]